<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Commands\Objects\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kt.Models\Kt.Data.Models.csproj" />
  </ItemGroup>
</Project>
